version: "3.8"

services:
    frontend:
        build:
            context: ./client/
            dockerfile: Dockerfile
        restart: always
            - 80:3000
        environment:
            host: 0.0.0.0
        networks:
            - outgoing
            - internal
    python_server:
        build:
            context: ./server/
            dockerfile: Dockerfile
        restart: always
        ports:
            - 8000:8000
        depends_on:
            - mongo_eu
            - mongo_us
            - data_eu
            - data_us
            - data_global
        environment:
            host: 0.0.0.0
        networks:
            - outgoing
            - internal
    mongo_eu:
        image: mongodb/mongodb-community-server:6.0-ubi8
        restart: always
        environment:
            MONGODB_INITDB_ROOT_USERNAME: root
            MONGODB_INITDB_ROOT_PASSWORD: pass
        ports:
            - 27017:27017
        volumes:
            - songs_eu:/data/db
        networks:
            - internal
    mongo_us:
        image: mongodb/mongodb-community-server:6.0-ubi8
        restart: always
        environment:
            MONGODB_INITDB_ROOT_USERNAME: root
            MONGODB_INITDB_ROOT_PASSWORD: pass
        ports:
            - 27018:27017
        volumes:
            - songs_us:/data/db
        networks:
            - internal
    data_global:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: pass
            POSTGRES_DB: data_global
        ports:
            - 5432:5432
        volumes:
            - data_global:/var/lib/postgresql/data
        networks:
            - internal
    data_eu:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: pass
            POSTGRES_DB: data_eu
        ports:
          - 5433:5432
        volumes:
          - data_eu:/var/lib/postgresql/data
        networks:
            - internal
    data_us:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: pass
            POSTGRES_DB: data_us
        ports:
            - 5434:5432
        volumes:
            - data_us:/var/lib/postgresql/data
        networks:
            - internal

volumes:
    songs_eu:
    songs_us:
    data_eu:
    data_us:
    data_global:

networks:
    outgoing:
        driver: bridge
    internal:
        driver: bridge