version: "3.8"

services:
    python_server:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - "8000:8000"
        depends_on:
            - mongo_eu
        environment:
            - host=0.0.0.0
        networks:
            - outgoing
            - internal
    mongo_eu:
        image: mongodb/mongodb-community-server:6.0-ubi8
        environment:
            - MONGODB_INITDB_ROOT_USERNAME=root
            - MONGODB_INITDB_ROOT_PASSWORD=pass
        ports:
            - "27017:27017"
        volumes:
            - data:/data/db
        networks:
            - internal

volumes:
    data:

networks:
    outgoing:
        driver: bridge
    internal:
        driver: bridge